import Head from "next/head";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Nosotros from "../components/Nosotros";
import Opiniones from "../components/Opiniones";
import Servicios from "../components/Servicios";
import Slider from "../components/Slider";
import { Slider2 } from "../components/Slider2";
import { SliderData } from "../components/SliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>XCIEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero
        heading="Ya conoces nuestros servicios?"
        message="Te ofrecemos servicios especializados de internet
                  dedicado empresarial y/o corporativo"
      />
      <Slider2 />
      <Servicios />

      <Opiniones />
      <Nosotros />
    </div>
  );
}
