
import Head from "next/head";
import Hero from "../components/Hero";
import Nosotros from "../components/Nosotros";
import Opiniones from "../components/Opiniones";
import Servicios from "../components/Servicios";
import Footer from '../components/Footer'
import {CardExpand} from '../components/ExpandCards/CardExpand'
export default function Home() {
  return (
    <div>
      <Head>
        <title>XCIEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Hero
        heading="Ya conoces nuestros servicios?"
        message="Te ofrecemos servicios especializados de internet
                  dedicado empresarial y/o corporativo"
      />
    <CardExpand/>
      <Servicios />
      <Opiniones />
      <Nosotros />
      <Footer/>
    </div>
  );
}
