import { useState, useEffect } from "react";
import Head from "next/head";
import Hero from "../components/Hero";
import Nosotros from "../components/Nosotros";
import Opiniones from "../components/Opiniones";
import Servicios from "../components/Servicios";
import Footer from "../components/Footer";
import { CardExpand } from "../components/ExpandCards/CardExpand";
import Parallax from '../pages/Parallax/index'
import Slider from "../components/Slider";
import PromocionApp from "../components/PromocionApp";


export default function Home() {
  const size = useWindowSize();

  function useWindowSize() {
    const [windowSize, setWindowSize] = useState({
      width: undefined,
      height: undefined,
    });

    useEffect(() => {
      if (typeof window !== "undefined") {
        function handleResize() {
          setWindowSize({
            width: window.innerWidth,
            height: window.innerHeight,
          });
        }

        window.addEventListener("resize", handleResize);

        handleResize();

        return () => window.removeEventListener("resize", handleResize);
      }
    }, []);
    return windowSize;
  }

  return (
    <div>
      <Head>
        <title>XCIEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossOrigin="anonymous"
        ></link>
      </Head>

      <Hero
        heading="Ya conoces nuestros servicios?"
        message="Te ofrecemos servicios especializados de internet
                  dedicado empresarial y/o corporativo"
      />
      <Servicios />
      <PromocionApp />
      <Nosotros />
      
      <Opiniones />

      <Footer />
    </div>
  );
}
